language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script: 
  - bash 'Tools/prepareBuildDependencies.bash.sh'
  - cd 'Build solutions/Traditional batch commands/'
  - bash buildSoftware.bash.sh
